--
-- PostgreSQL database dump
--

-- Dumped from database version 14.11 (Homebrew)
-- Dumped by pg_dump version 14.11 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: board; Type: TABLE; Schema: public; Owner: minthug
--

CREATE TABLE public.board (
    board_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone NOT NULL,
    title character varying(255),
    description text,
    activity_location character varying(255),
    member_id bigint,
    board_type character varying(255),
    activity_dates character varying(255),
    activity_times character varying(255)
);


ALTER TABLE public.board OWNER TO minthug;

--
-- Name: board_board_id_seq; Type: SEQUENCE; Schema: public; Owner: minthug
--

ALTER TABLE public.board ALTER COLUMN board_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.board_board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: minthug
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO minthug;

--
-- Name: image; Type: TABLE; Schema: public; Owner: minthug
--

CREATE TABLE public.image (
    image_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone NOT NULL,
    unique_name character varying(255),
    image_name character varying(255),
    s3url character varying(255),
    s3file_path character varying(255),
    board_id bigint,
    member_id bigint
);


ALTER TABLE public.image OWNER TO minthug;

--
-- Name: image_image_id_seq; Type: SEQUENCE; Schema: public; Owner: minthug
--

ALTER TABLE public.image ALTER COLUMN image_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member; Type: TABLE; Schema: public; Owner: minthug
--

CREATE TABLE public.member (
    member_id bigint NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone NOT NULL,
    email character varying(255),
    name character varying(255),
    nickname character varying(255),
    introduce character varying(255),
    phone_number character varying(255),
    password character varying(255),
    image_url character varying(255),
    social_id character varying(255),
    access_token character varying(255),
    refresh_token character varying(255),
    provider character varying(255),
    member_role character varying(255),
    member_type character varying(255)
);


ALTER TABLE public.member OWNER TO minthug;

--
-- Name: member_member_id_seq; Type: SEQUENCE; Schema: public; Owner: minthug
--

ALTER TABLE public.member ALTER COLUMN member_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: oauth_user; Type: TABLE; Schema: public; Owner: minthug
--

CREATE TABLE public.oauth_user (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    provider character varying(255) NOT NULL,
    provider_id character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    image_url character varying(255),
    member_id bigint
);


ALTER TABLE public.oauth_user OWNER TO minthug;

--
-- Name: oauth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: minthug
--

ALTER TABLE public.oauth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.oauth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: board; Type: TABLE DATA; Schema: public; Owner: minthug
--

COPY public.board (board_id, created_at, updated_at, title, description, activity_location, member_id, board_type, activity_dates, activity_times) FROM stdin;
11	2024-08-06 01:27:15.506821	2024-08-14 15:34:38.893787	test patch2	test	seoul	2	\N	MON	AFTERNOON,EVENING
\.


--
-- Data for Name: flyway_schema_history; Type: TABLE DATA; Schema: public; Owner: minthug
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1	init	SQL	V1__init.sql	-814003325	minthug	2024-07-30 23:52:09.352751	43	t
\.


--
-- Data for Name: image; Type: TABLE DATA; Schema: public; Owner: minthug
--

COPY public.image (image_id, created_at, updated_at, unique_name, image_name, s3url, s3file_path, board_id, member_id) FROM stdin;
38	2024-08-06 01:27:16.36542	2024-08-06 01:27:16.362247	dcb11286-e66f-4ed3-ac89-99fcb74171d2.jpeg	다운로드 (1).jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/082c1424-173a-4bb8-bf49-6d80a13ec972.jpeg	member/2/boards/11	11	\N
39	2024-08-06 01:36:43.201395	2024-08-06 01:36:43.180477	05ad5125-197a-4834-8b42-b8538e63aa29.jpeg	images.jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/06849b8a-447b-4b27-9ea5-54f598a4f77d.jpeg	member/2/boards/11	11	\N
40	2024-08-06 01:53:09.496938	2024-08-06 01:53:09.479518	2bc72353-6e00-4fc9-993e-8fbf158deca5.jpeg	images.jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/fd85a8c0-2b61-4222-aafe-fd3515574c1a.jpeg	member/2/boards/11	11	\N
41	2024-08-06 01:53:24.66448	2024-08-06 01:53:24.664128	c973f6bd-e99a-4af5-b5be-b98b7eae555d.jpeg	다운로드 (2).jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/f0e4e54f-7910-4c1e-b777-9417e909ec7f.jpeg	member/2/boards/11	11	\N
42	2024-08-06 01:53:33.258577	2024-08-06 01:53:33.258252	2b3d5d8c-1ad7-44c2-9502-cc48f578635f.jpeg	다운로드 (2).jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/3a7343f5-1ba4-4398-a7de-c6e9255a3500.jpeg	member/2/boards/11	11	\N
43	2024-08-06 02:01:18.677703	2024-08-06 02:01:18.652326	d6e9d174-197c-421f-b004-2f041a144f6a.jpg	istockphoto-1482199015-612x612.jpg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/1e441b6f-2341-4da0-93be-3613f4ff747e.jpg	member/2/boards/11	11	\N
44	2024-08-06 02:01:34.292883	2024-08-06 02:01:34.29257	cac15964-e442-442e-ac5c-21936354d544.jpg	pngtree-three-puppies-with-their-mouths-open-are-posing-for-a-photo-image_2902292.jpg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/160ae693-cf32-4ab5-8dd1-94413b8f2a52.jpg	member/2/boards/11	11	\N
45	2024-08-06 02:07:00.055136	2024-08-06 02:07:00.023227	ea586f16-2356-4c0c-ad11-0ca9da33b6d7.jpeg	다운로드 (1).jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/08c8bfa6-de3b-4189-8220-70dce0592e44.jpeg	member/2/boards/11	11	\N
46	2024-08-06 02:09:31.490841	2024-08-06 02:09:31.490627	86efbb01-0d74-46d8-94c4-b305bd05d4d8.jpeg	다운로드.jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/457ec10c-61a9-4370-9dd1-763f8c2809e9.jpeg	member/2/boards/11	11	\N
47	2024-08-06 02:13:01.121144	2024-08-06 02:13:01.088037	87066a47-a3d3-4fa4-a5fe-8ad83ac0fee5.png	test.png	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/fb24ecd9-0a8b-4052-b3f4-32efbba1ab5b.png	member/2/boards/11	11	\N
48	2024-08-06 02:16:57.921815	2024-08-06 02:16:57.900304	ecd79868-8c8e-4534-9bcf-ca02bbd4678d.jpeg	다운로드.jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/a5fef947-1ee6-4c28-8277-62978ad3d80d.jpeg	member/2/boards/11	11	\N
49	2024-08-06 02:17:16.092214	2024-08-06 02:17:16.091867	6a34dbca-2153-4b65-a311-eed21fa0b3f3.jpeg	다운로드 (4).jpeg	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/boards/11/824e23d8-2ebd-495b-85fc-cb16ca5bcb4f.jpeg	member/2/boards/11	11	\N
\.


--
-- Data for Name: member; Type: TABLE DATA; Schema: public; Owner: minthug
--

COPY public.member (member_id, created_at, updated_at, email, name, nickname, introduce, phone_number, password, image_url, social_id, access_token, refresh_token, provider, member_role, member_type) FROM stdin;
4	2024-08-05 22:15:53.198467	2024-09-23 16:28:32.539778	jkisimmortal4@gmail.com	김민석	\N	\N	\N	\N	https://lh3.googleusercontent.com/a/ACg8ocLHmPz8AI2EX3qZdD5Yh7OpI3UKRMLFxWJd2katTkeuji2etrtX=s96-c	108553246091781192919	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTcyNzA4MDExMiwiZW1haWwiOiJqa2lzaW1tb3J0YWw0QGdtYWlsLmNvbSJ9.36ir32CJC2xBEH6qqIaa0Pt-aH1Iec9Jj1eUkyTAA9ie79INXgmgeBpuGVP8MEk3JWAMtihvflgnVp7134sVnQ	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJSZWZyZXNoVG9rZW4iLCJleHAiOjE3Mjk2Njg1MTIsImVtYWlsIjoiamtpc2ltbW9ydGFsNEBnbWFpbC5jb20ifQ._ry3i-XNXoIiO9VMdkJjeB6Qst_zYCI_Lzj7dM8Km6GtTgWqp-C9vMoiXColbE4W4X4BlL2MoVq_4JHaBQoGSQ	google	USER	GOOGLE
3	2024-07-31 02:24:40.920205	2024-07-31 02:24:40.96387	vvsogi@gmail.com	김우석	\N	\N	\N	\N	https://lh3.googleusercontent.com/a/ACg8ocINhRCtIt_SWq2i4Kk4HdpL1eyjiLDUOK00HgMTB9lGcwKYlqWu=s96-c	117284599072019177951	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsImV4cCI6MTcyMjM2Mzg4MCwiZW1haWwiOiJ2dnNvZ2lAZ21haWwuY29tIn0.q4k5NqAjShy_gSsmwi7pihYCcS6JkfUTrBKapRBtaSbQVisPtjLN0-XIz-lbVggEdd44IK4h77bGTTJVcXbS8Q	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJSZWZyZXNoVG9rZW4iLCJleHAiOjE3MjQ5NTIyODAsImVtYWlsIjoidnZzb2dpQGdtYWlsLmNvbSJ9.bBMecFygUtJxhgR7mOSwVgZhbHvhSauEYPPh6H3vZV2w1dOPZAZ-_ltE0LabByQEzE72-DBCtbT-nGuWy8nkAg	google	USER	GOOGLE
2	2024-07-31 01:12:31.561097	2024-08-14 15:28:06.060514	jkisimmortal5@gmail.com	\N	thisTestId6	hi153	010-1234-1234	{bcrypt}$2a$10$Qyd11R0kLtWw9.nNHcpDKe.jyqn4rWeANLOQRx4vWFtzqJAqS4E76	https://sniff-step-s3-bucket.s3.ap-northeast-2.amazonaws.com/member/2/profile/547fb47f-3daa-49a9-9948-f0074effddad.jpeg	\N	eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJSZWZyZXNoVG9rZW4iLCJleHAiOjE3MjYyMDg4ODUsImVtYWlsIjoiamtpc2ltbW9ydGFsNUBnbWFpbC5jb20ifQ.0NcuNfMug6uHz7aPStkYEr6EGF4iCPYBM5o_gEZj-NEoHwvCkerVO8suoB1wliovvYIQBM-NFOKD1LmdAWhnag	\N	\N	USER	GENERAL
\.


--
-- Data for Name: oauth_user; Type: TABLE DATA; Schema: public; Owner: minthug
--

COPY public.oauth_user (id, email, provider, provider_id, name, image_url, member_id) FROM stdin;
\.


--
-- Name: board_board_id_seq; Type: SEQUENCE SET; Schema: public; Owner: minthug
--

SELECT pg_catalog.setval('public.board_board_id_seq', 12, true);


--
-- Name: image_image_id_seq; Type: SEQUENCE SET; Schema: public; Owner: minthug
--

SELECT pg_catalog.setval('public.image_image_id_seq', 50, true);


--
-- Name: member_member_id_seq; Type: SEQUENCE SET; Schema: public; Owner: minthug
--

SELECT pg_catalog.setval('public.member_member_id_seq', 5, true);


--
-- Name: oauth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: minthug
--

SELECT pg_catalog.setval('public.oauth_user_id_seq', 1, false);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: board pk_board; Type: CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT pk_board PRIMARY KEY (board_id);


--
-- Name: image pk_image; Type: CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT pk_image PRIMARY KEY (image_id);


--
-- Name: member pk_member; Type: CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT pk_member PRIMARY KEY (member_id);


--
-- Name: oauth_user pk_oauth_user; Type: CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.oauth_user
    ADD CONSTRAINT pk_oauth_user PRIMARY KEY (id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: minthug
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: board fk_board_on_member; Type: FK CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.board
    ADD CONSTRAINT fk_board_on_member FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: image fk_image_on_board; Type: FK CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT fk_image_on_board FOREIGN KEY (board_id) REFERENCES public.board(board_id);


--
-- Name: image fk_image_on_member; Type: FK CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT fk_image_on_member FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: oauth_user fk_oauth_user_on_member; Type: FK CONSTRAINT; Schema: public; Owner: minthug
--

ALTER TABLE ONLY public.oauth_user
    ADD CONSTRAINT fk_oauth_user_on_member FOREIGN KEY (member_id) REFERENCES public.member(member_id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: minthug
--

GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

