CREATE SEQUENCE IF NOT EXISTS member_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE board
(
    board_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title             VARCHAR(255),
    description       TEXT,
    activity_location VARCHAR(255),
    member_id         BIGINT,
    board_type        VARCHAR(255),
    activity_dates    VARCHAR(255),
    activity_times    VARCHAR(255),
    CONSTRAINT pk_board PRIMARY KEY (board_id)
);

CREATE TABLE image
(
    image_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    unique_name VARCHAR(255),
    image_name  VARCHAR(255),
    s3url       VARCHAR(255),
    s3file_path VARCHAR(255),
    board_id    BIGINT,
    member_id   BIGINT,
    CONSTRAINT pk_image PRIMARY KEY (image_id)
);

CREATE TABLE member
(
    member_id     BIGINT                      NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    email         VARCHAR(255),
    name          VARCHAR(255),
    nickname      VARCHAR(255),
    introduce     VARCHAR(255),
    phone_number  VARCHAR(255),
    password      VARCHAR(255),
    image_url     VARCHAR(255),
    social_id     VARCHAR(255),
    access_token  VARCHAR(255),
    refresh_token VARCHAR(255),
    provider      VARCHAR(255),
    member_role   VARCHAR(255),
    member_type   VARCHAR(255),
    CONSTRAINT pk_member PRIMARY KEY (member_id)
);

CREATE TABLE oauth_user
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    provider    VARCHAR(255)                            NOT NULL,
    provider_id VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    image_url   VARCHAR(255),
    member_id   BIGINT,
    CONSTRAINT pk_oauth_user PRIMARY KEY (id)
);

ALTER TABLE board
    ADD CONSTRAINT FK_BOARD_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_BOARD FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE image
    ADD CONSTRAINT FK_IMAGE_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE oauth_user
    ADD CONSTRAINT FK_OAUTH_USER_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);