server:
  port: 8081
  servlet:
    context-path: /api
    multipart:
      enabled: true # MultipartFile 업로드 활성화
      max-file-size: 2MB # 업로드할 수 있는 파일의 최대 크기
      max-request-size: 10MB # multipart/form-data 요청의 최대 크기
  tomcat:
    max-threads: 200
    accept-count: 100
    connection-timeout: 20000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

jwt:
  header: Authorization
  secret-key: "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.-DprLrW2OyqiAFiuWs14WO2TWp2EHtaX7a63dqrklk-xrjaZMrcPhpX4hkZw803SQx5HpGc-7VYBX8l82XlMZg"
  accessTokenExpireTime: 600000
  refreshTokenExpireTime: 2592000000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
