server:
  port: 8081
  servlet:
    context-path: /api
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  tomcat:
    max-threads: 200
    accept-count: 100
    connection-timeout: 20000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: minthug
    password: g1138745x
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

aws:
  access-key: ${cloud.aws.credentials.access-key} # 환경 변수를 사용하는 것이 좋음
  secret-key: ${cloud.aws.credentials.secret-key} # 환경 변수를 사용하는 것이 좋음
  s3:
    bucket: ${aws_s3_bucket} # 환경 변수를 사용하는 것이 좋음
    region: ${aws.s3.region} # 예시 리전, 실제 사용하는 리전으로 변경

jwt:
  header: Authorization
  secret-key: ${JWT_SECRET_KEY}
  accessTokenExpireTime: 600000 # 액세스 토큰의 만료 시간 (예: 600000ms = 10분)
  refreshTokenExpireTime: 2592000000 # 리프레시 토큰의 만료 시간 (예: 2592000000ms = 30일)
#jasypt:
#  encryptor:
#    password: secret # 암호화/복호화에 사용할 비밀 키

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
