on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            echo "Starting deployment process..."

            cd ~/sniff-step-nest
            git pull origin main
            docker-compose --profile services build

            echo "Stopping and removing backend service..."
            docker-compose stop backend
            docker-compose rm -f backend

            echo "Starting backend service..."
            docker-compose --profile services up -d

            echo "Deployment completed successfully!"

            docker exec -i nginx nginx -s reload
