on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            echo "Starting deployment process..."
            cd ~/Sniff-Step
            cd ~/backend
            git pull origin main
            
            echo "Building Docker image..."
            docker build -t sniff-step:latest .
            
            echo "Stopping and removing existing container..."
            docker stop sniff-step || true
            docker rm sniff-step || true
            
            echo "Starting new container..."
            docker run -d --name sniff-step -p 8081:8081 \
              -e SPRING_PROFILES_ACTIVE=prod \
              sniff-step:latest
            
            echo "Deployment completed successfully!"
            
            if docker ps | grep -q nginx; then
              docker exec nginx nginx -s reload
            else
              echo "Nginx container not found or not running"
            fi
