on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            echo "Starting deployment process..."
            cd ~/Sniff-Step
            cd ~/backend
            git pull origin main
            
            echo "Building Docker image..."
            docker build -t backend:latest .
            
            echo "Stopping and removing existing container..."
            docker stop backend || true
            docker rm backend || true
            
            echo "Starting new container..."
            docker run -d --name backend -p 8081:8081 \
              -e SPRING_PROFILES_ACTIVE=prod \
              backend:latest
            
            echo "Deployment completed successfully!"
            
            if docker ps | grep -q nginx; then
              docker exec nginx nginx -s reload
            else
              echo "Nginx container not found or not running"
            fi
